### ISSUE TITLE
Missing or invalid credentials when git pushing from a renkulab.io environment

### ISSUE THREAD

**Issue by mitch-volpi** [SwissDataScienceCenter/renku-notebooks#587] opened 2021-03-17 15:27 UTC
I get the following error, when pushing from a terminal of a renkulab.io online instance: 

```
Missing or invalid credentials.
Error: socket hang up
    at connResetException (internal/errors.js:610:14)
    at Socket.socketOnEnd (_http_client.js:453:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
```

At the same time, I get a window asking to insert my renkulab.io password, and when doing so, the repo pushes and everything goes smoothly. Screenshot attached. 

<img width="1531" alt="screenshot_2021-03-17_at_16 18 48" src="https://user-images.githubusercontent.com/13692772/111493117-8e97cd00-873d-11eb-8813-5a9276a0eb27.png">

edit: sometimes it also asks for the renkulab.io username

**Comment by rokroskar** [comment] 2021-03-17 15:39
cc @ableuler this looks like a problem with the git credentials proxy?

**Comment by mitch-volpi** [comment] 2021-03-18 09:28
Just for completeness, it first time it happened was from vscode, but credentials are also required when pushing from the jupyterlab terminal

**Comment by ableuler** [comment] 2021-03-27 21:33
Thanks for reporting this bug @mitch-volpi . Unfortunately I'm unable to reproduce this behaviour. Does this keep happening?

**Comment by ableuler** [comment] 2021-03-31 12:01
Closing as this problem doesn't seem to be reproducible for now. Please reopen if we see another occurrence of this or even have a clear path for reproducing it.

**Comment by ableuler** [comment] 2021-04-13 10:08
Reopening as there seems to be a way to reproduce this. @mitch-volpi would you ming launching another session from this project with the "auto fetch LFS data" option enabled and then execute `git config -l` and `git lfs version` inside that environment and post the output?  (ofc feel free to redact personal information in this output)

**Comment by ableuler** [comment] 2021-04-13 10:09
fyi @erbou .

**Comment by mitch-volpi** [comment] 2021-04-13 13:30
Hi @ableuler, sure no problems. Here the config: 
```
git config -l && git lfs version
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
user.name=<my name>
user.email=<my email>
credential.helper=store --file=/work/spca-decomposition/.git/credentials
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
remote.origin.url=https://renkulab.io/gitlab/ACE-ASAID/spca-decomposition.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
http.proxy=http://localhost:8080
http.sslverify=false
```

Here the version: 
```
git-lfs/2.8.0 (GitHub; linux amd64; go 1.12.6)
```

**Closed** 2021-04-15 08:40 UTC
Labels: bug
