### ISSUE TITLE
Connecting to server from notebooks-ui during spawn results in 500

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-notebooks#41] opened 2018-09-05 06:13 UTC
Clicking on `Connect` while the server is not ready results in a 500 page on jupyterhub.

**Comment by ebiiii** [comment] 2018-09-07 05:34
Maybe this is the cause:
```[2018-09-07 05:29:46 +0000] [8] [ERROR] Error handling request /jupyterhub/services/notebooks/eberlej/test-renku/b408a9cd335cb122eef4ae3bc0507f19c9ae6905/test.ipynb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/app/src/notebooks_service.py", line 91, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/src/notebooks_service.py", line 136, in decorated
    return f(user, *args, **kwargs)
  File "/app/src/notebooks_service.py", line 233, in notebook_status
    app.logger.debug(request.environ['HTTP_REFERER'])
KeyError: 'HTTP_REFERER'
```

**Comment by rokroskar** [comment] 2018-09-07 07:39
That should've been fixed, where are you running it? This only happens when you enter the url manually

**Comment by rokroskar** [comment] 2018-09-07 07:40
I think the reason is that JH returns a 400 somewhere that isn't being handled properly

**Comment by leafty** [comment] 2018-09-07 08:16
Just to say, this is low priority imho. It's quite rare to click on connect while the server is spawning.

**Comment by rokroskar** [comment] 2018-09-07 08:18
sure, but to clarify -- you clicked connect in the "notebook UI" where it lists the running servers, right? That whole setup needs to be fixed, but yes, I think I've also encountered it there.

**Comment by rokroskar** [comment] 2018-09-07 08:29
For some reason, JH tries to spawn the server again when you try to connect: 

```
[I 2018-09-07 08:22:49.155 JupyterHub log:158] 302 GET /jupyterhub/user/rokroskar/rokroskar-test-567e45d/ -> /jupyterhub/hub/user/rokroskar/rokroskar-test-567e45d/ (@10.39.0.0) 1.25ms
[D 2018-09-07 08:22:49.203 JupyterHub base:603] Initiating spawn for rokroskar
[D 2018-09-07 08:22:49.203 JupyterHub base:609] 1/64 concurrent spawns
[D 2018-09-07 08:22:49.203 JupyterHub base:612] 1 active servers
[I 2018-09-07 08:22:49.282 JupyterHub spawners:84] starting with args: --ip="0.0.0.0" --port=8888 --notebook-dir="/home/jovyan/work" --NotebookApp.default_url="/lab" --debug
[D 2018-09-07 08:22:49.282 JupyterHub spawners:86] user options: {}
```

This second spawn is *after* the first spawn is underway. Note the empty user options. This is what they look like on the first spawn:

```
[D 2018-09-07 08:22:46.157 JupyterHub spawners:86] user options: {'branch': 'master', 'commit_sha': '567e45df39ce2c5ce044339887a8b5fc67eea007', 'namespace': 'rokroskar', 'notebook': None, 'project': 'test', 'image_pull_secrets': ['renku-notebooks-registry']}
```

Where this second spawn comes from I have no idea. I guess it could happen if JH automatically spawns a new server on a `GET` but that would be strange (the button on the notebooks UI goes straight to JH and does not go through the notebook service).

**Comment by rokroskar** [comment] 2018-11-26 10:45
Leaving this open but removing it from the `0.3.0` milestone.

**Comment by rokroskar** [comment] 2019-06-13 06:16
I believe it has been fixed with the new UI implementation.

**Closed by rokroskar** 2019-06-13 06:16 UTC
Labels: bug
