### ISSUE TITLE
Create template for a RenkuLab specific custom resource object definition

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-notebooks#623] opened 2021-04-22 07:05 UTC
The custom resource objects will need some git-related add-ons which are currently in the init-container and the git-https-proxy components. The goal of this issue is to have a method which takes a `UserServer` object and executes a call to the custom api to create that object.

**Comment by olevski** [comment] 2021-06-02 13:40
This is a duplicate of #624.

**Closed by olevski** 2021-06-02 13:40 UTC
